---

- hosts: all
  connection: local
  gather_facts: yes

  #tasks:
  #  - include_tasks: roles/notificacoes-externas/send_telegram.yml msg="Iniciando a aplicação do compliance"
  roles:
    - ../roles/compliance-so
    - ../roles/aws-route53
    - ../roles/vivo-elb
    - ../roles/aws-elb
