- hosts: app
  connection: local
  become: true
  gather_facts: yes

  #tasks:
  #  - include_tasks: roles/notificacoes-externas/send_telegram.yml msg="Iniciando a implantação do APP"
  roles:
    - ../roles/apache
    - ../roles/wordpress
