---
# tasks file for compliance-so

- name: Selinux permisseve
  selinux:
    policy: targeted
    state: permissive

- name: Stop and disable firewalld.
  service:
  name: firewalld
    state: stopped
    enabled: False
