# Configures Wordpress
---

- name: Verifiy Host Ansible
  shell: cat /root/.stack/cron-bootsrap/bootstrap-cron.conf | grep HOST_ANSIBLE  | cut -d\" -f2
  register: host_ansible

- name: Apache config file for Wordpress
  template:
    src: wordpress.conf.j2
    dest: "{{ wordpress_httpd_configuration }}"
    owner: root
    group: root
    mode: '0644'
    setype: httpd_config_t
  notify: restart httpd
  tags: wordpress

- name: Download Salts
  get_url:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    dest: "{{ wordpress_directory }}/wp-salts.php"
    seuser: system_u
    setype: httpd_sys_script_exec_t
    force: no
  notify: restart httpd
  tags: wordpress

- name: Insert PHP start tag in Salts file
  lineinfile:
    dest: "{{ wordpress_directory }}/wp-salts.php"
    line: '<?php'
    state: present
    insertbefore: BOF
  notify: restart httpd
  tags: wordpress

- name: Insert PHP end tag in Salts file
  lineinfile:
    dest: "{{ wordpress_directory }}/wp-salts.php"
    line: '?>'
    state: present
    insertafter: EOF
  notify: restart httpd
  tags: wordpress

- name: Wordpress config file app one
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_configuration }}"
    owner: root
    group: apache
    mode: '0640'
    setype: etc_t
  notify: restart httpd
  tags: wordpress
  when: host_ansible.stdout == "app1poc.{{ fqdn_route }}"

- name: Wordpress config file app two
  template:
    src: wp-config_2.php.j2
    dest: "{{ wordpress_configuration }}"
    owner: root
    group: apache
    mode: '0640'
    setype: etc_t
  notify: restart httpd
  tags: wordpress
  when: host_ansible.stdout != "app1poc.{{ fqdn_route }}"

- name: Allow Apache to access database over the network if necessary
  seboolean:
    name: httpd_can_network_connect_db
    state: on
    persistent: yes
  when: ansible_selinux.status == 'enabled' and wordpress_database_host != 'localhost'
  tags: wordpress
