---
# tasks file for wordpress

#- include_vars: "{{ ansible_distribution }}.yml"
- include_vars: "main.yml"
  tags:
    - wordpress
- include: install.yml
- include: config.yml
- include: plugins.yml
- include: themes.yml
