---
- name: Verifiy Host Ansible
  shell: cat /root/.stack/cron-bootsrap/bootstrap-cron.conf | grep HOST_ANSIBLE  | cut -d\" -f2
  register: host_ansible

- name: Check status slave bd one
  mysql_replication:
    mode: getslave
  when: host_ansible.stdout == "db1poc.{{ fqdn_route }}"
  register: status_slave

- name: Alter status slave bd one
  mysql_replication:
    mode: changemaster
    master_host: "db2poc.{{ fqdn_route }}"
    master_user: poc
    master_password: poc
    master_connect_retry: 300
  when: host_ansible.stdout == "db1poc.{{ fqdn_route }}" and status_slave.Is_Slave == false

- name: start slave bd one
  mysql_replication:
    mode: startslave
  tags: mariadb
  when: host_ansible.stdout == "db1poc.{{ fqdn_route }}" and status_slave.Is_Slave == false

- name: Check status slave bd two
  mysql_replication:
    mode: getslave
  when: host_ansible.stdout == "db2poc.{{ fqdn_route }}"
  register: status_slave_bd2

- name: Alter status slave bd two
  mysql_replication:
    mode: changemaster
    master_host: "db1poc.{{ fqdn_route }}"
    master_user: poc
    master_password: poc
    master_connect_retry: 300
  with_items: "{{ mariadb_users_replication }}"
  when: host_ansible.stdout == "db2poc.{{ fqdn_route }}" and status_slave_bd2.Is_Slave == false

- name: start slave bd two
  mysql_replication:
    mode: startslave
  when: host_ansible.stdout == "db2poc.{{ fqdn_route }}" and status_slave_bd2.Is_Slave == false
