# roles/mariadb/tasks/config.yml
---
- name: Verifiy Host Ansible
  shell: cat /root/.stack/cron-bootsrap/bootstrap-cron.conf | grep HOST_ANSIBLE  | cut -d\" -f2
  register: host_ansible

- name: Install network config file bd one
  template:
    src: etc_bd_my.cnf.d_network.cnf.j2
    dest: "{{ mariadb_config_network }}"
    mode: 0644
  when: host_ansible.stdout_lines == "db1poc"
  tags: mariadb

- name: Install network config file bd two
  template:
    src: etc_bd2_my.cnf.d_network.cnf.j2
    dest: "{{ mariadb_config_network }}"
    mode: 0644
  when: host_ansible.stdout_lines == "db2poc"
  tags: mariadb

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness }}"
    state: present
  tags: mariadb
