---
- name: Verifiy Host Ansible
  shell: cat /root/.stack/cron-bootsrap/bootstrap-cron.conf | grep HOST_ANSIBLE  | cut -d\" -f2
  register: host_ansible

- name: Check status slave bd one
  mysql_replication:
    mode: getslave
  when: host_ansible.stdout == "db1poc"
  register: status_slave

- name: Alter status slave bd one
  mysql_replication:
    mode: changemaster
    master_host: db2poc.gcsb.com.br
    master_user: poc
    master_password: poc
  when: host_ansible.stdout == "db1poc" and status_slave.Is_Slave == false

- name: start slave bd one
  mysql_replication:
    mode: startslave
  tags: mariadb
  when: host_ansible.stdout == "db1poc" and status_slave.Is_Slave == false

- name: Check status slave bd two
  mysql_replication:
    mode: getslave
  when: host_ansible.stdout == "db2poc"
  register: status_slave_bd2

- name: Alter status slave bd two
  mysql_replication:
    mode: changemaster
    master_host: db1poc.gcsb.com.br
    master_user: poc
    master_password: poc
  with_items: "{{ mariadb_users_replication }}"
  when: host_ansible.stdout == "db2poc" and status_slave_bd2.Is_Slave == false

- name: start slave bd two
  mysql_replication:
    mode: startslave
  when: host_ansible.stdout == "db2poc" and status_slave_bd2.Is_Slave == false
