# roles/mariadb/tasks/users.yml
---

- name: Verifiy Host Ansible
  shell: cat /root/.stack/cron-bootsrap/bootstrap-cron.conf | grep HOST_ANSIBLE  | cut -d\" -f2
  register: host_ansible

- name: Create the users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host|default('localhost') }}"
    priv: "{{ item.priv }}"
    state: present
  with_items: "{{ mariadb_users }}"
  when: host_ansible.stdout == "db1poc.{{ fqdn_route }}"
