---
- name: Verifiy Ip Public
  get_url:
    url: https://api.ipify.org?format=txt
    dest: /tmp/HOST_IP_PUBLICO.txt
    mode: 0440

- name: Validade ip Public
  shell: cat /tmp/HOST_IP_PUBLICO.txt
  register: ip_public_host

- name: Verifiy Host Ansible
  shell: cat /root/.stack/cron-bootsrap/bootstrap-cron.conf | grep HOST_ANSIBLE  | cut -d\" -f2
  register: host_ansible

- name: Insert IP db1poc in Route 53
  route53:
      aws_access_key: "{{ aws_access_key_route }}"
      aws_secret_key: "{{ aws_secret_key_route }}"
      state: present
      zone: gcsb.com.br
      record: db1poc.gcsb.com.br
      type: A
      value: "{{ ip_public_host.stdout }}"
      overwrite: yes
      wait: yes
  when: host_ansible.stdout == "db1poc"

- name: Insert IP db2poc in Route 53
  route53:
      aws_access_key: "{{ aws_access_key_route }}"
      aws_secret_key: "{{ aws_secret_key_route }}"
      state: present
      zone: gcsb.com.br
      record: db2poc.gcsb.com.br
      type: A
      value: "{{ ip_public_host.stdout }}"
      overwrite: yes
      wait: yes
  when: host_ansible.stdout == "db2poc"

- name: Insert IP app1poc in Route 53
  route53:
      aws_access_key: "{{ aws_access_key_route }}"
      aws_secret_key: "{{ aws_secret_key_route }}"
      state: present
      zone: gcsb.com.br
      record: app1poc.gcsb.com.br
      type: A
      value: "{{ ip_public_host.stdout }}"
      overwrite: yes
      wait: yes
  when: host_ansible.stdout == "app1poc"
